# helm template jenkins bitnami/jenkins

---
# Source: jenkins/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: jenkins
  namespace: "default"
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-11.0.1
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  jenkins-password: "VTdXU1RTeTJNaw=="
---
# Source: jenkins/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  namespace: "default"
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-11.0.1
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Helm
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
---
# Source: jenkins/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: "default"
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-11.0.1
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: jenkins
---
# Source: jenkins/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: "default"
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-11.0.1
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
      app.kubernetes.io/instance: jenkins
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins
        helm.sh/chart: jenkins-11.0.1
        app.kubernetes.io/instance: jenkins
        app.kubernetes.io/managed-by: Helm
      annotations:
        checksum/secrets: aec13d09f344869dc17f84d6d5a544f88895d146209349e7630ddfcd236f70a6
    spec:
      serviceAccountName: default

      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: jenkins
                    app.kubernetes.io/instance: jenkins
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:

      securityContext:
        fsGroup: 1001
      containers:
        - name: jenkins
          image: docker.io/bitnami/jenkins:2.361.1-debian-11-r0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: JENKINS_USERNAME
              value: "user"
            - name: JENKINS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jenkins
                  key: jenkins-password
            - name: JENKINS_HOME
              value: "/bitnami/jenkins/home"
            - name: DISABLE_JENKINS_INITIALIZATION
              value: "no"
            - name: JENKINS_HOST
              value: ""
            - name: JENKINS_EXTERNAL_HTTP_PORT_NUMBER
              value: "80"
            - name: JENKINS_EXTERNAL_HTTPS_PORT_NUMBER
              value: "443"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          resources:
            limits: {}
            requests:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - name: jenkins-data
              mountPath: /bitnami/jenkins
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins